version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - echo Logging in to Amazon ECR Private...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $IMAGE_URI
      - echo Build completed. Image available at $IMAGE_URI
      - printf '{"ImageURI":"%s"}' $IMAGE_URI > imageDetail.json

artifacts:
  files:
    - imageDetail.json
