"""Generate a FAISS-compatible test index for the semantic search service.

Two modes are supported via ``--backend``:

``random`` (default)
    Unit-normalised random vectors (seeded, reproducible).  No AWS calls.
    Use for infrastructure / filter / API wiring validation only.  Scores
    will be meaningless because the vectors have no relationship to the text.

``bedrock``
    Real embeddings generated by calling AWS Bedrock Titan embed-text-v1.
    Scores will reflect genuine semantic similarity.  Requires AWS credentials
    and Bedrock access in the target region.

Usage::

    # Random index (no AWS) — infrastructure validation only
    uv run python scripts/generate_test_index.py

    # Real Bedrock embeddings — semantic search validation
    uv run python scripts/generate_test_index.py --backend bedrock \
        --region us-east-1 --output ./bedrock_index

    # Build with Bedrock and upload to S3 in one step
    uv run python scripts/generate_test_index.py --backend bedrock \
        --region us-east-1 --upload

    # Custom output directory
    uv run python scripts/generate_test_index.py --output /tmp/my_index

    # Larger random corpus
    uv run python scripts/generate_test_index.py --extra 200
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path
from typing import List

# Ensure the project root is on sys.path so 'semantic_search' is importable
# when the script is executed directly (e.g. `uv run python scripts/...`).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import numpy as np

from semantic_search.embeddings.base import EmbeddingInput
from semantic_search.vectorstores.faiss_store import NumpyVectorStore, VectorRecord

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
LOGGER = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DIM = 1536  # Bedrock Titan embed-text-v1 / text-embedding-ada-002 dimension
BEDROCK_MODEL = "amazon.titan-embed-text-v1"
DEFAULT_OUTPUT = "./test_index"
S3_BUCKET = "semantic-search-dev-faiss-index"
S3_PREFIX = "vector_store/current"

# ---------------------------------------------------------------------------
# Themed document corpus
# Four categories with distinct metadata so filter queries are testable.
# ---------------------------------------------------------------------------

DOCS: List[dict] = [
    # --- technology ---
    {"title": "Introduction to vector databases",       "category": "technology",  "source": "blog",  "year": 2024},
    {"title": "Semantic search with embeddings",        "category": "technology",  "source": "blog",  "year": 2024},
    {"title": "RAG architecture patterns",              "category": "technology",  "source": "paper", "year": 2023},
    {"title": "Approximate nearest-neighbour search",   "category": "technology",  "source": "paper", "year": 2023},
    {"title": "HNSW graph indexing explained",          "category": "technology",  "source": "blog",  "year": 2022},
    {"title": "Embedding models comparison 2024",       "category": "technology",  "source": "blog",  "year": 2024},
    {"title": "Chunking strategies for LLM context",   "category": "technology",  "source": "paper", "year": 2024},
    # --- engineering ---
    {"title": "Python async best practices",            "category": "engineering", "source": "docs",  "year": 2023},
    {"title": "FastAPI dependency injection patterns",  "category": "engineering", "source": "docs",  "year": 2024},
    {"title": "Type-safe dataclasses in Python",        "category": "engineering", "source": "blog",  "year": 2023},
    {"title": "Testing strategies for ML pipelines",   "category": "engineering", "source": "blog",  "year": 2024},
    {"title": "Observability for microservices",        "category": "engineering", "source": "docs",  "year": 2022},
    {"title": "CI/CD for containerised Python apps",   "category": "engineering", "source": "blog",  "year": 2023},
    # --- devops ---
    {"title": "AWS Fargate cost optimisation",          "category": "devops",      "source": "docs",  "year": 2024},
    {"title": "Terraform module design patterns",       "category": "devops",      "source": "docs",  "year": 2023},
    {"title": "ECS task definition best practices",    "category": "devops",      "source": "docs",  "year": 2024},
    {"title": "CloudWatch alarms and dashboards",      "category": "devops",      "source": "docs",  "year": 2023},
    {"title": "Blue-green deployments on ECS",         "category": "devops",      "source": "blog",  "year": 2022},
    {"title": "S3 lifecycle rules for cost savings",   "category": "devops",      "source": "blog",  "year": 2024},
    # --- product ---
    {"title": "Search UX patterns that convert",        "category": "product",     "source": "blog",  "year": 2023},
    {"title": "Relevance tuning for e-commerce",        "category": "product",     "source": "paper", "year": 2024},
    {"title": "A/B testing search ranking changes",     "category": "product",     "source": "blog",  "year": 2023},
    {"title": "User feedback loops for search quality", "category": "product",     "source": "paper", "year": 2024},
    {"title": "Analytics for internal search tools",   "category": "product",     "source": "docs",  "year": 2022},
    # --- edge cases ---
    {"title": "Ünïcödé tïtlé wïth spécïal chars",      "category": "technology",  "source": "blog",  "year": 2021},
    {"title": "",                                       "category": "engineering", "source": "docs",  "year": 2020},
    {"title": "No category record",                     "source": "unknown",                          "year": 2019},
]


def _make_unit_vector(rng: np.random.Generator, dim: int) -> np.ndarray:
    """Generate a single unit-normalised random float32 vector.

    Args:
        rng: NumPy random generator instance.
        dim: Vector dimensionality.

    Returns:
        A 1-D float32 array of length ``dim`` with L2 norm of 1.
    """
    vec = rng.standard_normal(dim).astype(np.float32)
    vec /= np.linalg.norm(vec)
    return vec


def build_records(
    docs: List[dict],
    dim: int,
    rng: np.random.Generator,
    id_prefix: str = "doc",
) -> List[VectorRecord]:
    """Build a list of VectorRecords from document metadata dicts.

    Args:
        docs: List of metadata dicts. Each must contain at least a ``title``
            key; all other keys are stored as metadata.
        dim: Vector dimensionality passed to ``_make_unit_vector``.
        rng: NumPy random generator used to produce synthetic vectors.
        id_prefix: Prefix for generated record IDs (``{prefix}-{i:04d}``).

    Returns:
        A list of :class:`VectorRecord` objects ready for insertion.
    """
    records = []
    for i, doc in enumerate(docs):
        vec = _make_unit_vector(rng, dim)
        records.append(
            VectorRecord(
                record_id=f"{id_prefix}-{i:04d}",
                vector=vec,
                metadata=doc,
            )
        )
    return records


def build_bedrock_index(
    docs: List[dict],
    region: str,
    model: str = BEDROCK_MODEL,
    id_prefix: str = "doc",
) -> NumpyVectorStore:
    """Build a real semantic index by embedding document titles via Bedrock.

    Each document's ``title`` field is sent to the Bedrock embedding model.
    The returned store uses cosine metric and contains genuine semantic vectors
    so that search results reflect real meaning, not random noise.

    Args:
        docs: List of metadata dicts.  The ``title`` key is used as the text
            to embed; all keys are preserved as record metadata.
        region: AWS region for the Bedrock runtime (e.g. ``"us-east-1"``).
        model: Bedrock model ID (default: Titan embed-text-v1).
        id_prefix: Prefix for generated record IDs (``{prefix}-{i:04d}``).

    Returns:
        A populated :class:`NumpyVectorStore` with real embedding vectors.

    Raises:
        SystemExit: On provider initialisation or embedding failure.
    """
    import semantic_search.embeddings.bedrock  # noqa: F401 — registers 'bedrock' factory
    from semantic_search.embeddings.factory import get_provider
    from semantic_search.pipeline.embedding_pipeline import EmbeddingPipeline

    LOGGER.info("Initialising Bedrock provider: region=%s  model=%s", region, model)
    try:
        provider = get_provider("bedrock", {"region": region, "model": model})
    except Exception as exc:  # noqa: BLE001
        LOGGER.critical("Failed to initialise Bedrock provider: %s", exc)
        raise SystemExit(1) from exc

    inputs = [
        EmbeddingInput(
            record_id=f"{id_prefix}-{i:04d}",
            text=doc.get("title") or f"doc-{i:04d}",  # fallback for empty titles
            metadata=doc,
        )
        for i, doc in enumerate(docs)
    ]

    store = NumpyVectorStore(dimension=DIM, metric="cosine")
    pipeline = EmbeddingPipeline(provider, store, batch_size=10)

    LOGGER.info("Embedding %d documents via Bedrock ...", len(inputs))
    result = pipeline.run(inputs)
    LOGGER.info(
        "Bedrock embedding complete: %d succeeded, %d failed.",
        result.succeeded,
        result.failed,
    )
    if result.failed:
        LOGGER.warning("Failed record IDs: %s", result.failed_ids)

    return store


def upload_to_s3(local_path: str, bucket: str, prefix: str) -> None:
    """Upload a saved index directory to S3.

    Uploads ``vectors.npy`` and ``metadata.json`` from ``local_path`` to
    ``s3://{bucket}/{prefix}/``.  Requires the ``boto3`` package and AWS
    credentials resolvable by the default credential chain.

    Args:
        local_path: Local directory containing ``vectors.npy`` and
            ``metadata.json`` as produced by :meth:`NumpyVectorStore.save`.
        bucket: S3 bucket name.
        prefix: S3 key prefix (no leading or trailing slash).

    Raises:
        ImportError: If ``boto3`` is not installed.
        Exception: Re-raises any S3 client errors.
    """
    try:
        import boto3  # type: ignore[import]
    except ImportError as exc:
        raise ImportError(
            "boto3 is required for --upload. Install it with: pip install boto3"
        ) from exc

    s3 = boto3.client("s3")
    for filename in ("vectors.npy", "metadata.json"):
        local_file = os.path.join(local_path, filename)
        s3_key = f"{prefix}/{filename}"
        LOGGER.info("Uploading s3://%s/%s ...", bucket, s3_key)
        s3.upload_file(local_file, bucket, s3_key)
        LOGGER.info("  OK")


def parse_args(argv: List[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments.

    Args:
        argv: Argument list (defaults to ``sys.argv[1:]`` when ``None``).

    Returns:
        Parsed :class:`argparse.Namespace`.
    """
    parser = argparse.ArgumentParser(
        description="Generate a synthetic test FAISS index for semantic-search."
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help=f"Local directory to write the index (default: {DEFAULT_OUTPUT!r})",
    )
    parser.add_argument(
        "--upload",
        action="store_true",
        help=(
            f"Upload the index to s3://{S3_BUCKET}/{S3_PREFIX}/ after saving. "
            "Requires boto3 and valid AWS credentials."
        ),
    )
    parser.add_argument(
        "--extra",
        type=int,
        default=0,
        metavar="N",
        help="Generate N additional synthetic records beyond the curated corpus.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducible vector generation (default: 42).",
    )
    parser.add_argument(
        "--backend",
        choices=["random", "bedrock"],
        default="random",
        help=(
            "'random' (default): seeded synthetic vectors, no AWS. "
            "'bedrock': real Titan embeddings via AWS Bedrock."
        ),
    )
    parser.add_argument(
        "--region",
        default="us-east-1",
        help="AWS region for Bedrock (only used with --backend bedrock, default: us-east-1).",
    )
    return parser.parse_args(argv)


def main(argv: List[str] | None = None) -> int:
    """Entry point for the test index generator.

    Args:
        argv: Argument list forwarded to :func:`parse_args`.

    Returns:
        Exit code (0 on success, 1 on error).
    """
    args = parse_args(argv)

    if args.backend == "bedrock":
        if args.extra > 0:
            LOGGER.warning("--extra is ignored when --backend bedrock is used.")
        store = build_bedrock_index(DOCS, region=args.region)
    else:
        rng = np.random.default_rng(args.seed)
        records = build_records(DOCS, DIM, rng)
        if args.extra > 0:
            extra_docs = [
                {"title": f"Synthetic doc {i}", "category": "synthetic", "source": "generated"}
                for i in range(args.extra)
            ]
            records += build_records(extra_docs, DIM, rng, id_prefix="syn")
            LOGGER.info("Added %d extra synthetic records.", args.extra)
        store = NumpyVectorStore(dimension=DIM, metric="cosine")
        store.upsert(records)  # upsert: idempotent, no duplicate warnings on re-runs

    store.save(args.output)
    LOGGER.info("Saved %d records to %r", len(store._vectors), args.output)

    if args.upload:
        upload_to_s3(args.output, S3_BUCKET, S3_PREFIX)
        LOGGER.info(
            "Index live at s3://%s/%s/",
            S3_BUCKET,
            S3_PREFIX,
        )
        LOGGER.info(
            "Set VECTOR_STORE_PATH=s3://%s/%s in your ECS task definition to activate /readyz.",
            S3_BUCKET,
            S3_PREFIX,
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
