"""Generate a vector index from one or more CSV files.

Extracts rows from the configured CSV path (supports glob patterns for
multiple files), embeds the concatenated text fields using the selected
embedding provider, and saves the resulting NumpyVectorStore for local
server validation.

Two backends are supported via ``--backend``:

``spot`` (default)
    Local hash-based stub (SentenceTransformers-compatible, no AWS required).
    Scores will not reflect true semantic similarity until a real
    SentenceTransformers endpoint is wired in.

``bedrock``
    Real embeddings generated by calling AWS Bedrock Titan embed-text-v1.
    Scores will reflect genuine semantic similarity.  Requires AWS credentials
    and Bedrock access in the target region.

Usage::

    # Default: data/sample.csv, text=title+content, id=id, meta=category (Spot)
    uv run python scripts/generate_csv_index.py

    # Bedrock backend — real semantic embeddings from CSV data
    uv run python scripts/generate_csv_index.py \\
        --backend bedrock --region us-east-1 \\
        --csv ./data/sample.csv --output ./csv_bedrock_index

    # Custom CSV path and field mapping
    uv run python scripts/generate_csv_index.py \\
        --csv ./data/my_data.csv \\
        --text-fields title,body \\
        --id-field record_id \\
        --metadata-fields category,status \\
        --output ./my_csv_index

    # Glob pattern for multiple files
    uv run python scripts/generate_csv_index.py --csv './data/*.csv'

Detail fields and text fields may overlap intentionally.  A column such as
``content`` is a good embedding source (captured via ``--text-fields``) *and*
a useful drill-down field (captured via ``--detail-fields``).  When a field
appears in both, it is embedded into the vector **and** stored under ``_detail``
in the metadata — it will not appear as a visible tag on the search result
card unless the user expands the drill-down panel.  This keeps cards concise
while still surfacing the full text on demand.
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from semantic_search.config.app import PreprocessingConfig, build_preprocessing_pipeline
from semantic_search.config.metadata import split_metadata
from semantic_search.embeddings.base import EmbeddingInput
from semantic_search.vectorstores.faiss_store import NumpyVectorStore

logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
LOGGER = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Defaults (match data/sample.csv column names)
# ---------------------------------------------------------------------------

DEFAULT_CSV = "./data/sample.csv"
DEFAULT_TEXT_FIELDS = "title,content"
DEFAULT_ID_FIELD = "id"
DEFAULT_METADATA_FIELDS = "category,author"
DEFAULT_DETAIL_FIELDS = "content"
DEFAULT_OUTPUT = "./csv_spot_index"
DEFAULT_MODEL_SPOT = "sentence-transformers/all-MiniLM-L6-v2"
DEFAULT_DIM_SPOT = 384
DEFAULT_MODEL_BEDROCK = "amazon.titan-embed-text-v1"
DEFAULT_DIM_BEDROCK = 1536


def extract_inputs(
    csv_path: str,
    text_fields: List[str],
    id_field: Optional[str],
    metadata_fields: List[str],
    detail_fields: Optional[List[str]] = None,
    preprocessing_pipeline: Optional[Any] = None,
) -> List[EmbeddingInput]:
    """Extract records from CSV files and convert to EmbeddingInputs.

    Args:
        csv_path: Path or glob pattern to one or more CSV files.
        text_fields: Ordered list of column names to concatenate as the
            embeddable text payload.
        id_field: Column used as the record identifier.  When ``None`` the
            connector generates a fallback ID from filename and row index.
        metadata_fields: Columns stored as filterable metadata.
        detail_fields: Optional columns stored under ``_detail`` in metadata
            for drill-down display.
        preprocessing_pipeline: Optional
            :class:`~semantic_search.preprocessing.PreprocessingPipeline` to
            clean and optionally chunk records before embedding.

    Returns:
        List of EmbeddingInput objects ready for the embedding pipeline.

    Raises:
        SystemExit: If the connector cannot read the CSV or finds no records.
    """
    from semantic_search.ingestion import DataSourceError, get_connector

    detail_fields = detail_fields or []
    detail_field_set: Set[str] = set(detail_fields)
    # Pass combined list to the connector so all fields are extracted.
    all_metadata_fields = metadata_fields + [
        f for f in detail_fields if f not in metadata_fields
    ]

    LOGGER.info("Extracting from CSV: %s", csv_path)
    config: dict = {
        "path": csv_path,
        "text_fields": text_fields,
        "metadata_fields": all_metadata_fields,
    }
    if id_field:
        config["id_field"] = id_field

    try:
        connector = get_connector("csv", config)
        records = list(connector.extract())
    except DataSourceError as exc:
        LOGGER.critical("Failed to extract from CSV: %s", exc)
        raise SystemExit(1) from exc

    if preprocessing_pipeline is not None:
        records = list(preprocessing_pipeline.process(records))
        LOGGER.info("  After preprocessing: %d records", len(records))

    inputs = [
        EmbeddingInput(
            record_id=r.record_id,
            text=r.text,
            metadata=split_metadata(dict(r.metadata), detail_field_set),
        )
        for r in records
    ]
    LOGGER.info("  Extracted %d records", len(inputs))
    return inputs


def build_csv_index(
    csv_path: str,
    text_fields: List[str],
    id_field: Optional[str],
    metadata_fields: List[str],
    detail_fields: Optional[List[str]] = None,
    backend: str = "spot",
    model_name: Optional[str] = None,
    dimension: Optional[int] = None,
    region: str = "us-east-1",
    preprocessing_pipeline: Optional[Any] = None,
) -> NumpyVectorStore:
    """Extract CSV records and embed them using the selected provider.

    Args:
        csv_path: Path or glob pattern to one or more CSV files.
        text_fields: Columns concatenated to produce embeddable text.
        id_field: Column used as record identifier (``None`` for auto-ID).
        metadata_fields: Columns stored as filterable metadata.
        detail_fields: Optional columns stored under ``_detail`` in metadata
            for drill-down display.
        backend: Embedding backend — ``"spot"`` (local stub) or ``"bedrock"``
            (real AWS Bedrock embeddings).
        model_name: Logical model identifier reported in result metadata.
            Defaults to the backend-specific model if ``None``.
        dimension: Embedding vector dimensionality (must match the model).
            Defaults to the backend-specific dimension if ``None``.
        region: AWS region for Bedrock (only used when ``backend="bedrock"``).
        preprocessing_pipeline: Optional pipeline to clean/chunk records
            before embedding.

    Returns:
        A populated NumpyVectorStore ready to be saved and served.

    Raises:
        SystemExit: On provider initialisation failure or if no records are
            found to embed.
    """
    from semantic_search.embeddings.factory import get_provider
    from semantic_search.pipeline.embedding_pipeline import EmbeddingPipeline

    # Resolve backend-specific defaults
    if backend == "bedrock":
        import semantic_search.embeddings.bedrock  # noqa: F401 — registers 'bedrock' factory
        model_name = model_name or DEFAULT_MODEL_BEDROCK
        dimension = dimension or DEFAULT_DIM_BEDROCK
        provider_config: Dict[str, Any] = {"region": region, "model": model_name}
        batch_size = 10
    else:
        import semantic_search.embeddings.spot  # noqa: F401 — registers 'spot' factory
        model_name = model_name or DEFAULT_MODEL_SPOT
        dimension = dimension or DEFAULT_DIM_SPOT
        provider_config = {"model_name": model_name, "dimension": dimension}
        batch_size = 50

    LOGGER.info(
        "Initialising %s provider: model=%s  dimension=%d",
        backend, model_name, dimension,
    )
    try:
        provider = get_provider(backend, provider_config)
    except Exception as exc:  # noqa: BLE001
        LOGGER.critical("Failed to initialise %s provider: %s", backend, exc)
        raise SystemExit(1) from exc

    inputs = extract_inputs(
        csv_path, text_fields, id_field, metadata_fields, detail_fields,
        preprocessing_pipeline=preprocessing_pipeline,
    )
    if not inputs:
        LOGGER.critical("No records extracted — nothing to embed.")
        raise SystemExit(1)

    store = NumpyVectorStore(dimension=dimension, metric="cosine")
    pipeline = EmbeddingPipeline(provider, store, batch_size=batch_size)

    LOGGER.info("Embedding %d records via %s ...", len(inputs), backend)
    result = pipeline.run(inputs)
    LOGGER.info(
        "Embedding complete: %d succeeded, %d failed.",
        result.succeeded,
        result.failed,
    )
    if result.failed:
        LOGGER.warning("Failed record IDs: %s", result.failed_ids)

    return store


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    """Parse command-line arguments.

    Args:
        argv: Argument list (defaults to ``sys.argv[1:]`` when ``None``).

    Returns:
        Parsed :class:`argparse.Namespace`.
    """
    parser = argparse.ArgumentParser(
        description="Generate a Spot-embedded FAISS index from CSV file(s)."
    )
    parser.add_argument(
        "--csv",
        default=None,
        help=f"Path or glob to CSV file(s) (default: {DEFAULT_CSV!r})",
    )
    parser.add_argument(
        "--text-fields",
        default=None,
        help=f"Comma-separated text columns (default: {DEFAULT_TEXT_FIELDS!r})",
    )
    parser.add_argument(
        "--id-field",
        default=None,
        help=f"Column used as record ID (default: {DEFAULT_ID_FIELD!r})",
    )
    parser.add_argument(
        "--metadata-fields",
        default=None,
        help=f"Comma-separated metadata columns (default: {DEFAULT_METADATA_FIELDS!r})",
    )
    parser.add_argument(
        "--detail-fields",
        default=None,
        help=(
            f"Comma-separated columns stored under _detail for drill-down display "
            f"(default: {DEFAULT_DETAIL_FIELDS!r}). "
            "May overlap with --text-fields: overlapping columns are embedded into "
            "the vector AND stored in _detail, so they won't appear as visible "
            "metadata tags unless the user expands the drill-down panel."
        ),
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help=f"Output directory for the index (default: {DEFAULT_OUTPUT!r})",
    )
    parser.add_argument(
        "--backend",
        choices=["spot", "bedrock"],
        default="spot",
        help=(
            "Embedding backend: 'spot' (default, local hash stub) or "
            "'bedrock' (real AWS Bedrock Titan embeddings)."
        ),
    )
    parser.add_argument(
        "--region",
        default="us-east-1",
        help="AWS region for Bedrock (only used with --backend bedrock, default: us-east-1).",
    )
    parser.add_argument(
        "--model-name",
        default=None,
        help=(
            f"Model identifier (default: {DEFAULT_MODEL_SPOT!r} for spot, "
            f"{DEFAULT_MODEL_BEDROCK!r} for bedrock)"
        ),
    )
    parser.add_argument(
        "--dimension",
        type=int,
        default=None,
        help=(
            f"Embedding vector dimensionality (default: {DEFAULT_DIM_SPOT} for spot, "
            f"{DEFAULT_DIM_BEDROCK} for bedrock)"
        ),
    )
    parser.add_argument(
        "--config",
        default=None,
        help="Path to a source YAML config file (e.g. config/sources/sample_csv.yaml)",
    )
    parser.add_argument(
        "--app-config",
        default=None,
        help="Path to config directory containing app.yaml (e.g. ./config)",
    )
    parser.add_argument(
        "--no-preprocessing",
        action="store_true",
        default=False,
        help="Disable all preprocessing (cleaning and chunking) regardless of config.",
    )
    return parser.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    """Entry point for the CSV Spot index generator.

    Args:
        argv: Argument list forwarded to :func:`parse_args`.

    Returns:
        Exit code (0 on success, 1 on error).
    """
    args = parse_args(argv)

    # --- Optional YAML config loading --------------------------------------
    src_cfg = None
    app_cfg = None
    if args.config:
        import yaml
        from semantic_search.config.source import parse_source_config

        with open(args.config) as fh:
            try:
                raw = yaml.safe_load(fh)
            except yaml.YAMLError as exc:
                LOGGER.critical("Failed to parse YAML config %s: %s", args.config, exc)
                raise SystemExit(1) from exc
        src_cfg = parse_source_config(Path(args.config).stem, raw)
        LOGGER.info("Loaded source config: %s", args.config)

    if args.app_config:
        from semantic_search.config.app import load_app_config

        app_cfg = load_app_config(Path(args.app_config))
        LOGGER.info("Loaded app config from: %s", args.app_config)

    # --- Resolve fields: CLI > source YAML > defaults ----------------------
    csv_path = args.csv or (
        src_cfg.connector.config["path"]
        if src_cfg and src_cfg.connector.config.get("path")
        else DEFAULT_CSV
    )

    text_fields_raw = args.text_fields or (
        ",".join(src_cfg.text_fields) if src_cfg and src_cfg.text_fields else DEFAULT_TEXT_FIELDS
    )
    text_fields = [f.strip() for f in text_fields_raw.split(",") if f.strip()]

    metadata_fields_raw = args.metadata_fields or (
        ",".join(src_cfg.metadata_fields)
        if src_cfg and src_cfg.metadata_fields
        else DEFAULT_METADATA_FIELDS
    )
    metadata_fields = [f.strip() for f in metadata_fields_raw.split(",") if f.strip()]

    if args.detail_fields is not None:
        detail_fields = [f.strip() for f in args.detail_fields.split(",") if f.strip()]
    elif src_cfg is not None:
        detail_fields = list(src_cfg.detail_fields)  # honours explicit empty []
    else:
        detail_fields = [f.strip() for f in DEFAULT_DETAIL_FIELDS.split(",") if f.strip()]

    id_field = (
        args.id_field
        or (src_cfg.id_field if src_cfg and src_cfg.id_field else DEFAULT_ID_FIELD)
    ) or None

    # Resolve backend and its defaults
    backend = args.backend
    default_model = DEFAULT_MODEL_BEDROCK if backend == "bedrock" else DEFAULT_MODEL_SPOT
    default_dim = DEFAULT_DIM_BEDROCK if backend == "bedrock" else DEFAULT_DIM_SPOT

    model_name = args.model_name or (app_cfg.embedding.model if app_cfg else default_model)

    dimension = args.dimension
    if dimension is None:
        if app_cfg:
            dimension = app_cfg.embedding.dimension
        elif src_cfg is None:
            dimension = default_dim
        else:
            from semantic_search.config.models import resolve_dimension

            try:
                dimension = resolve_dimension(model_name, None)
            except Exception as exc:  # ModelPresetError
                LOGGER.critical("Cannot resolve dimension for model '%s': %s", model_name, exc)
                raise SystemExit(1) from exc

    # Build preprocessing pipeline (CLI flag > app config > built-in defaults)
    preprocessing_pipeline = None
    if not args.no_preprocessing:
        pp_cfg = app_cfg.preprocessing if app_cfg else PreprocessingConfig()
        preprocessing_pipeline = build_preprocessing_pipeline(pp_cfg)
        if preprocessing_pipeline is not None:
            LOGGER.info(
                "Preprocessing enabled: clean=%s  chunk=%s  chunk_size=%d  overlap=%d",
                pp_cfg.clean,
                pp_cfg.chunk,
                pp_cfg.chunk_size,
                pp_cfg.overlap,
            )

    store = build_csv_index(
        csv_path=csv_path,
        text_fields=text_fields,
        id_field=id_field,
        metadata_fields=metadata_fields,
        detail_fields=detail_fields,
        backend=backend,
        model_name=model_name,
        dimension=dimension,
        region=args.region,
        preprocessing_pipeline=preprocessing_pipeline,
    )
    store.save(args.output)
    LOGGER.info("Saved %d records to %r", len(store), args.output)

    return 0


if __name__ == "__main__":
    sys.exit(main())
